import React, { useState, useMemo } from 'react';
import {
  Clock,
  X,
  Copy,
  Check,
  TrendingUp,
  TrendingDown,
  Users,
  Award,
  Zap,
  Shield,
  Layers
} from 'lucide-react';
import { computePlayingTimeStats } from '../services/matchStatsService';
import '../styles/sidelineHud.css';

/**
 * PlayingTimeModal - Real-time Athlete Participation & Rotations Tracker
 * 
 * Provides hard data on playing time distribution:
 * - Rallies/points played on court
 * - Playing time %
 * - Sets appeared in
 * - Rotations played count & rotational diversity
 * - On-court Plus/Minus (+/- net score impact)
 */
export default function PlayingTimeModal({
  isOpen,
  onClose,
  roster = [],
  pointHistory = [],
  matchStats = {},
  currentLineup = {},
  teamName = 'Our Team'
}) {
  if (!isOpen) return null;

  const [selectedSetFilter, setSelectedSetFilter] = useState('ALL');
  const [toastMessage, setToastMessage] = useState('');

  // Filter points if set filter is selected
  const activePoints = useMemo(() => {
    if (selectedSetFilter === 'ALL') return pointHistory;
    return pointHistory.filter(pt => pt.setNumber === Number(selectedSetFilter));
  }, [pointHistory, selectedSetFilter]);

  // Compute playing time stats
  const playingStats = useMemo(() => {
    return computePlayingTimeStats(activePoints, roster, matchStats, currentLineup);
  }, [activePoints, roster, matchStats, currentLineup]);

  const totalPointsCount = activePoints.length;

  const showToast = (msg) => {
    setToastMessage(msg);
    setTimeout(() => setToastMessage(''), 2500);
  };

  const handleCopyReport = () => {
    const lines = [
      `⏱️ PLAYING TIME & ROTATIONS REPORT — ${teamName}`,
      `Match: vs ${matchStats?.opponentName || 'Opponent'} (Set Filter: ${selectedSetFilter})`,
      `Total Rallies: ${totalPointsCount}`,
      `--------------------------------------------------`,
      `#   PLAYER            POS   PTS   PCT   SETS  ROT   +/-`,
      `--------------------------------------------------`
    ];

    playingStats.forEach(s => {
      const numStr = `#${s.player?.number || ''}`.padEnd(4, ' ');
      const nameStr = (s.player?.name || 'Player').slice(0, 16).padEnd(17, ' ');
      const posStr = (s.player?.position || '--').slice(0, 4).padEnd(5, ' ');
      const ptsStr = `${s.ralliesPlayed}`.padStart(3, ' ');
      const pctStr = `${s.percentagePlayed}%`.padStart(5, ' ');
      const setsStr = `${s.setsPlayed}`.padStart(3, ' ');
      const rotStr = `${s.rotationsCount}`.padStart(3, ' ');
      const pmStr = (s.plusMinus > 0 ? `+${s.plusMinus}` : `${s.plusMinus}`).padStart(5, ' ');

      lines.push(`${numStr} ${nameStr} ${posStr} ${ptsStr} ${pctStr}  ${setsStr}   ${rotStr}  ${pmStr}`);
    });

    lines.push(`--------------------------------------------------`);
    lines.push(`Generated by GoStandOverThere Sideline PWA`);

    navigator.clipboard.writeText(lines.join('\n')).then(() => {
      showToast('Playing time report copied!');
    }).catch(() => {
      showToast('Report copied');
    });
  };

  return (
    <div className="r2-modal-overlay" onClick={onClose}>
      <div
        className="pt-modal-card"
        onClick={(e) => e.stopPropagation()}
        role="dialog"
        aria-modal="true"
        aria-label="Playing Time & Rotations Tracker"
      >
        {/* Header */}
        <div className="pt-modal-header">
          <div style={{ display: 'flex', alignItems: 'center', gap: '0.65rem' }}>
            <div
              style={{
                width: '38px',
                height: '38px',
                borderRadius: '10px',
                background: 'linear-gradient(135deg, rgba(56, 189, 248, 0.2), rgba(14, 165, 233, 0.35))',
                border: '1px solid #38bdf8',
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
                color: '#38bdf8'
              }}
            >
              <Clock size={20} />
            </div>
            <div>
              <div style={{ fontSize: '1.1rem', fontWeight: 800, color: '#ffffff' }}>
                Playing Time & Rotations Tracker
              </div>
              <div style={{ fontSize: '0.75rem', color: '#94a3b8' }}>
                Objective participation data, on-court points, and plus-minus ratings
              </div>
            </div>
          </div>

          <button
            type="button"
            className="r2-btn-close"
            onClick={onClose}
            title="Close Playing Time Tracker"
          >
            <X size={18} />
          </button>
        </div>

        {/* Body */}
        <div className="pt-modal-body">
          {/* Controls Ribbon */}
          <div
            style={{
              display: 'flex',
              flexWrap: 'wrap',
              alignItems: 'center',
              justifyContent: 'space-between',
              gap: '0.75rem',
              background: 'rgba(30, 41, 59, 0.5)',
              padding: '0.55rem 0.85rem',
              borderRadius: '12px',
              border: '1px solid rgba(255, 255, 255, 0.08)'
            }}
          >
            {/* Set Filter Pills */}
            <div style={{ display: 'flex', alignItems: 'center', gap: '0.35rem' }}>
              <span style={{ fontSize: '0.72rem', color: '#94a3b8', fontWeight: 700, textTransform: 'uppercase' }}>
                Scope:
              </span>
              {['ALL', 1, 2, 3, 4, 5].map(sKey => (
                <button
                  key={sKey}
                  type="button"
                  onClick={() => setSelectedSetFilter(String(sKey))}
                  style={{
                    background: selectedSetFilter === String(sKey) ? '#0284c7' : 'rgba(15, 23, 42, 0.7)',
                    border: `1px solid ${selectedSetFilter === String(sKey) ? '#38bdf8' : 'rgba(255, 255, 255, 0.1)'}`,
                    color: selectedSetFilter === String(sKey) ? '#ffffff' : '#cbd5e1',
                    padding: '0.2rem 0.55rem',
                    borderRadius: '6px',
                    fontSize: '0.74rem',
                    fontWeight: 700,
                    cursor: 'pointer'
                  }}
                >
                  {sKey === 'ALL' ? 'Full Match' : `Set ${sKey}`}
                </button>
              ))}
            </div>

            {/* Total Points Badge & Copy Button */}
            <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
              <span style={{ fontSize: '0.75rem', color: '#94a3b8' }}>
                Total Rallies: <strong style={{ color: '#38bdf8' }}>{totalPointsCount}</strong>
              </span>

              <button
                type="button"
                className="hud-btn"
                onClick={handleCopyReport}
                title="Copy playing time table to clipboard"
              >
                <Copy size={13} />
                <span>Copy Summary</span>
              </button>
            </div>
          </div>

          {/* Playing Time Table */}
          <div style={{ overflowX: 'auto', background: 'rgba(15, 23, 42, 0.7)', borderRadius: '14px', border: '1px solid rgba(255, 255, 255, 0.08)' }}>
            <table className="pt-table">
              <thead>
                <tr>
                  <th>Player</th>
                  <th>Position</th>
                  <th>Points on Court</th>
                  <th>Playing Time %</th>
                  <th>Sets</th>
                  <th>Rotations</th>
                  <th>Plus / Minus (+/-)</th>
                  <th>Impact</th>
                </tr>
              </thead>
              <tbody>
                {playingStats.map(stat => {
                  const p = stat.player;
                  const isPositive = stat.plusMinus > 0;
                  const isNegative = stat.plusMinus < 0;

                  return (
                    <tr key={p?.id || stat.playerId || Math.random()}>
                      <td>
                        <div style={{ display: 'flex', alignItems: 'center', gap: '0.45rem' }}>
                          <strong style={{ color: '#38bdf8', fontSize: '0.9rem' }}>#{p?.number}</strong>
                          <span style={{ fontWeight: 700 }}>{p?.name || 'Player'}</span>
                          {p?.isCaptain && (
                            <span style={{ fontSize: '0.62rem', color: '#f59e0b', border: '1px solid #f59e0b', padding: '0 0.3rem', borderRadius: '99px', fontWeight: 800 }}>
                              C
                            </span>
                          )}
                        </div>
                      </td>
                      <td>
                        <span style={{ fontSize: '0.72rem', color: '#94a3b8', textTransform: 'uppercase', fontWeight: 700 }}>
                          {p?.position || '—'}
                        </span>
                      </td>
                      <td>
                        <strong style={{ color: '#ffffff', fontSize: '0.88rem' }}>{stat.ralliesPlayed}</strong>
                        <span style={{ color: '#64748b', fontSize: '0.72rem', marginLeft: '3px' }}>/ {stat.totalMatchRallies}</span>
                      </td>
                      <td>
                        <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
                          <div className="pt-bar-bg">
                            <div className="pt-bar-fill" style={{ width: `${stat.percentagePlayed}%` }} />
                          </div>
                          <span style={{ fontWeight: 800, fontSize: '0.78rem', color: stat.percentagePlayed >= 50 ? '#34d399' : '#cbd5e1' }}>
                            {stat.percentagePlayed}%
                          </span>
                        </div>
                      </td>
                      <td>
                        <span style={{ fontWeight: 700 }}>{stat.setsPlayed}</span>
                      </td>
                      <td>
                        <div style={{ display: 'flex', alignItems: 'center', gap: '0.25rem', flexWrap: 'wrap' }}>
                          <span style={{ fontWeight: 700 }}>{stat.rotationsCount}</span>
                          {stat.rotationsList.length > 0 && (
                            <span style={{ fontSize: '0.65rem', color: '#64748b' }}>
                              (R{stat.rotationsList.join(', R')})
                            </span>
                          )}
                        </div>
                      </td>
                      <td>
                        <span className={`pt-plus-minus ${isPositive ? 'positive' : isNegative ? 'negative' : 'even'}`}>
                          {isPositive ? `+${stat.plusMinus}` : stat.plusMinus}
                        </span>
                      </td>
                      <td>
                        <div style={{ fontSize: '0.7rem', color: '#94a3b8' }}>
                          {stat.kills > 0 && <span style={{ color: '#34d399', marginRight: '4px' }}>{stat.kills}k</span>}
                          {stat.aces > 0 && <span style={{ color: '#38bdf8', marginRight: '4px' }}>{stat.aces}a</span>}
                          {stat.blocks > 0 && <span style={{ color: '#f59e0b', marginRight: '4px' }}>{stat.blocks}b</span>}
                          {stat.errors > 0 && <span style={{ color: '#f87171' }}>{stat.errors}e</span>}
                          {stat.kills === 0 && stat.aces === 0 && stat.blocks === 0 && stat.errors === 0 && '—'}
                        </div>
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>

          {/* Coach Insight Footer */}
          <div style={{ fontSize: '0.74rem', color: '#94a3b8', fontStyle: 'italic', display: 'flex', alignItems: 'center', gap: '0.4rem', padding: '0.25rem 0.5rem' }}>
            <span style={{ color: '#38bdf8', fontWeight: 700 }}>💡 Coach Tip:</span>
            <span>
              Plus/Minus (+/-) shows your team's scoring differential while each player was on court. Use this along with rotation diversity to ensure balanced development and optimal late-set lineups.
            </span>
          </div>
        </div>

        {/* Toast confirmation */}
        {toastMessage && (
          <div className="r2-toast">
            <Check size={16} />
            <span>{toastMessage}</span>
          </div>
        )}
      </div>
    </div>
  );
}
